export const invoiceData = [
  {
    id: 0,
    status: "pending",
    invoiceCode : '#XM9141',
    invoiceName: "Graphic Design",
    billerName: "Alex Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate:  "19 Aug, 2021",
    dueDate:  "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.00,
    items: [
      {
        id: 2,
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice:  156,
      },
      {
        id:3,
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.00,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  },
  {
    id: 1,
    status: "pending",
    invoiceCode : '#XM2121',
    invoiceName: "Graphic Design",
    billerName: "Alex Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate:  "19 Aug, 2021",
    dueDate:  "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.00,
    items: [
      {
        id: 4,
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice:  156,
      },
      {
        id:9,
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.00,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  },
  {
    id: 2,
    status: "Paid",
    invoiceCode : '#XM45321',
    invoiceName: "Graphic Design",
    billerName: "Alex Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate:  "19 Aug, 2021",
    dueDate:  "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.00,
    items: [
      {
        id: 4,
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice:  156,
      },
      {
        id:9,
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.00,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  }
];

