export const invoiceData = [
  {
    _id: 0,
    status: "Complete",
    invoiceCode: "#XM2345",
    invoiceName: "AI Design",
    billerName: "Porsha Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate: "19 Aug, 2021",
    dueDate: "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.0,
    items: [
      {
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice: 156,
      },
      {
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.0,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  },
  {
    _id: 1,
    status: "Complete",
    invoiceCode: "#XM2345",
    invoiceName: "AI Design",
    billerName: "Porsha Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate: "19 Aug, 2021",
    dueDate: "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.0,
    items: [
      {
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice: 156,
      },
      {
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.0,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  },
  {
    _id: 2,
    status: "Complete",
    invoiceCode: "#XM2345",
    invoiceName: "AI Design",
    billerName: "Porsha Grim",
    billerEmail: "alexgrim@gmail.com",
    billerAddress: "84 Church Way Bradford BD1 9PB United Kingdom",
    billedDate: "19 Aug, 2021",
    dueDate: "19 Aug, 2021",
    totalAmountCurrency: "£",
    totalAmount: 556.0,
    items: [
      {
        itemName: "Banner Design",
        qty: 1,
        unitPrice: 156,
        itemCurrency: "£",
        totalItemPrice: 156,
      },
      {
        itemName: "Email Design",
        qty: 2,
        unitPrice: 200.0,
        itemCurrency: "£",
        totalItemPrice: 200,
      },
    ],
  },
];

